### ISSUE TITLE
Is it correct to modify "state variable" directly?

### ISSUE THREAD

**Issue by infotim** [shanplourde/react-hooks-form-util#1]
> https://reactjs.org/docs/hooks-state.html

Official documentaion says that you should use setter received from `useState()` call to modify "state variable".

But I found that `inputValues` modified directly. 

https://github.com/shanplourde/react-hooks-form-util/blob/14a32a9aa0b1f0aa746d8d5cacf5651cc09b0fdb/src/components/form/use-form.js#L10-L12
https://github.com/shanplourde/react-hooks-form-util/blob/14a32a9aa0b1f0aa746d8d5cacf5651cc09b0fdb/src/components/form/use-form.js#L92

Not sure if it is a bug.

**Comment by shanplourde** [comment]
Hi @infotim thanks for asking and sorry about the delay getting back. I was stuck on this during development. Originally I was trying to use the setter, but it seems like React doesn't like when you call a custom hook, get an object back, and then invoke functions on the custom object that themselves call setters of `useState`, since it causes a re-render. So this re-render limits the use of setters and it seems you have to mutate state directly. 

Here's the React error the solution gets when the setter is used:

> Too many re-renders. React limits the number of renders to prevent an infinite loop.

I was able to work around this (by returning inputs[id] in `addInput` if it existed) but it didn't result in a working solution. `onChange` etc. events wouldn't fire. 

I guess it might be better to use `useRef` since it would be more explicit that the solution is mutating state. Let me know if you know of any thoughts on this. 

Thanks
Shan

**Comment by infotim** [comment]
> Too many re-renders. React limits the number of renders to prevent an infinite loop.

Originally I needed dynamic number of inputs and ability to focus them from my code. My first attempts were getting the same error.

> I guess it might be better to use `useRef` since it would be more explicit that the solution is mutating state. 

I tried this and it works for me so far.

```javascript
import React, { useRef } from 'react'
import uniqid from 'uniqid'
import { useImmer } from 'use-immer'

function useInputs() {
    const [input, setInput] = useImmer({})
    const refs = useRef({})

    const setRef = (id) => (node) => {
        if (node === null) {
            delete refs.current[id]
        } else {
            refs.current[id] = node
        }
    }

    const addInput = (props) => {
        const id = uniqid()
        if (typeof input[id] === 'undefined') {

            setInput(draft => {
                draft[id] = {
                    value: '',
                    ref: setRef(id),
                    onChange: e => {
                        const value = e.target.value
                        setInput(draft => {
                            draft[id].value = value
                        })
                    },
                    ...props,
                }
            })
            return id
        }
    }

    const removeInput = (id) => {
        delete refs.current[id]
        setInput(draft => {
            delete draft[id]
        })
    }

    return {
        input,
        refs,
        api: {
            addInput,
            removeInput
        }
    }
}
```

**Comment by shanplourde** [comment]
I switched the useState hooks that I was mutating to useRef as well now. It's a better choice since the code is at least being explicit about doing state mutations.
